"""Pydantic models for AI-powered resume enrichment."""

from typing import Literal

from pydantic import BaseModel, Field

from app.models.resume.schemas import ComprehensiveAnalysisData


class EnrichmentItem(BaseModel):
    """An item identified by AI as needing enrichment."""

    item_id: str
    item_type: str
    title: str
    subtitle: str | None = None
    current_description: list[str] = Field(default_factory=list)
    weakness_reason: str


class EnrichmentQuestion(BaseModel):
    """A clarifying question generated by AI for an item."""

    question_id: str
    item_id: str
    question: str
    placeholder: str = ""


class AnalysisResponse(BaseModel):
    """Response from AI resume analysis."""

    items_to_enrich: list[EnrichmentItem] = Field(default_factory=list)
    questions: list[EnrichmentQuestion] = Field(default_factory=list)
    analysis_summary: str | None = None


class AnswerInput(BaseModel):
    """User's answer to a clarifying question."""

    question_id: str
    answer: str


class AnalyzeRequest(BaseModel):
    """Request to analyze resume data for enrichment."""

    resume_data: ComprehensiveAnalysisData


class EnhanceRequest(BaseModel):
    """Request to generate enhanced descriptions from answers."""

    resume_data: ComprehensiveAnalysisData
    answers: list[AnswerInput]


class EnhancedDescription(BaseModel):
    """AI-generated enhanced description for an item."""

    item_id: str
    item_type: str
    title: str
    original_description: list[str] = Field(default_factory=list)
    enhanced_description: list[str] = Field(default_factory=list)


class EnhancementPreview(BaseModel):
    """Preview of all enhancements before applying."""

    enhancements: list[EnhancedDescription] = Field(default_factory=list)


class ApplyEnhancementsRequest(BaseModel):
    """Request to apply enhancements to resume data."""

    resume_data: ComprehensiveAnalysisData
    enhancements: list[EnhancedDescription]


RegenerateItemType = Literal["experience", "project", "skills"]


class RegenerateItemInput(BaseModel):
    """Input for a single item to regenerate."""

    item_id: str
    item_type: RegenerateItemType
    title: str
    subtitle: str | None = None
    current_content: list[str] = Field(default_factory=list)


class RegenerateRequest(BaseModel):
    """Request to regenerate selected resume items."""

    items: list[RegenerateItemInput]
    instruction: str = Field(max_length=2000)
    output_language: str = "en"


class RegeneratedItem(BaseModel):
    """Regenerated content for one item."""

    item_id: str
    item_type: RegenerateItemType
    title: str
    subtitle: str | None = None
    original_content: list[str] = Field(default_factory=list)
    new_content: list[str] = Field(default_factory=list)
    diff_summary: str = ""


class RegenerateItemError(BaseModel):
    """A non-fatal error for a single item regeneration request."""

    item_id: str
    item_type: RegenerateItemType
    title: str
    subtitle: str | None = None
    message: str


class RegenerateResponse(BaseModel):
    """Response with all regenerated items."""

    regenerated_items: list[RegeneratedItem] = Field(default_factory=list)
    errors: list[RegenerateItemError] = Field(default_factory=list)


class ApplyRegeneratedRequest(BaseModel):
    """Request to apply regenerated items to resume data."""

    resume_data: ComprehensiveAnalysisData
    items: list[RegeneratedItem]
